### ISSUE TITLE
db: remove character limit in genetic modification field (cell table)

### ISSUE THREAD

**Issue by dwrobel1** [hmslincs/hmslincs#336]
The genetic modification field in the cell table currently cannot accommodate lengthy annotations that are necessary to describe genetically modified cell lines.

**Comment by seanderickson** [comment]
Yeah, in general, the "character varying(n)" and "char(n)" types have been deprecated for postgreSQL use, see:
http://www.postgresql.org/docs/9.1/static/datatype-character.html
and here's a simplified discussion:
http://people.planetpostgresql.org/dfetter/index.php?/archives/24-VARCHARn-Considered-Harmful.html

- I'll remove all the varchar designations for the Cell class in the current branch update in the works.
