### ISSUE TITLE
edits requested by EW

### ISSUE THREAD

**Issue by gberriz** [hmslincs/hmslincs#343]
To http://lincs.hms.harvard.edu/explore/adaptive_drug_resistance/:

- Correct the title to “pathway” instead of “pathways”.
- Correct the verb in the PLSR loadings browser descriptive text: "Shown
across all 10 cell lines are the PLSR loadings…"

To
http://lincs.hms.harvard.edu/explore/adaptive_drug_resistance/plsr_loadings
/:

- Correct the title to “pathway” instead of “pathways”.
- Make V600E a superscript instead of a parenthetical note in this
sentence: "Each scatterplot shows the relationship between the first and
second PLSR model loadings from an analysis of the covariation of
molecular signals with cell viability and apoptosis fraction in
BRAF(V600E/D) melanoma cell lines."

- Fix this sentence: “Each plotted point corresponds either to RPPA a
measurement/time point combination, or to viability.” I suspect this is
supposed to say: “Each plotted point corresponds either to an RPPA
measurement/time point combination or to viability.”

To http://lincs.hms.harvard.edu/explore/adaptive_drug_resistance/vips/:

- Correct the title to “pathway” instead of “pathways”.
- Fix this sentence (remove the rogue “map”): "The graph on the left maps
the VIP scores (as reported by Fallahi-Sichani et al.
<http://dx.doi.org/10.15252/msb.20145877>) for any chosen combination of
cell line and timepoint onto a schematic diagram of processes (in italics)
and factors involved in immediate-early signaling.”
- Add the citation/link to this sentence: "(See Figures 2 and 4 of op
cit)."

**Comment by jmuhlich** [comment]
Closed by 35d873f.
