### ISSUE TITLE
some values of items_per_page lead to improperly formatted pages

### ISSUE THREAD

**Issue by gberriz** [hmslincs/hmslincs#370]
minor bug

For example, the following link leads to a page with screwed up formatting:

https://lincs.hms.harvard.edu/db/datasets/?items_per_page=200&search=kinomescan

**Comment by seanderickson** [comment]
Notes:
- using "items_per_page" not in the choices does not work
- numbering for the range should be 1 based, not zero based i.e. ("0 to 25 of 160 Datasets")

- to fix, don't render the drop-down if a number that is not in the drop-down list is used.
