### ISSUE TITLE
firefox: "This connection is untrusted" page when visiting https://lincs.hms.harvard.edu

### ISSUE THREAD

**Issue by gberriz** [hmslincs/hmslincs#371]
I get this with some browsers:

![image](https://cloud.githubusercontent.com/assets/438371/9673782/e51a250e-5275-11e5-903d-713129e040d2.png)

I understand that we cannot solve this problem directly, but it remains an issue.

**Comment by jmuhlich** [comment]
RC fixed the certificate chain and Gabe reported this is resolved.
