### ISSUE TITLE
db: xlwt (xls) file downloads have a limit of 65535 rows

### ISSUE THREAD

**Issue by seanderickson** [hmslincs/hmslincs#386]
* this affects the new dataset 20236, for #357 
* switch to openpxyl (xlsx) to accomodate the larger file size

@jmuhlich

**Comment by jmuhlich** [comment]
Ugh. xlrd can read xlsx these days but I guess xlwt never gained the corresponding functionality. Check out XlsxWriter too -- I read on a StackOverflow comment that its API is closer to xlwt's than openpyxl's is, so the porting might be easier.

**Comment by jmuhlich** [comment]
Also, do we change the URLs to `.../results?output_type=.xlsx` or do we silently make `output_type=.xls` just send xlsx files now? We do have a bunch of URLs in other pages that point directly to .xls downloads.

**Comment by seanderickson** [comment]
I was going with openpyxl because we already have it in our requirements.txt; I've also used XlsxWriter, so from an API standpoint there's no advantage to me either way.

Jeez, I don't know what to do about the extension - could we redirect "xls" requests?

**Comment by jmuhlich** [comment]
I guess we should make the code accept both .xls and .xlsx, try to fix 
our own links, and watch the logs to see if there are any external links 
to .xls URLs.
