### ISSUE TITLE
db: 3 digit batch id's recognized by importer but not in views.py method

### ISSUE THREAD

**Issue by seanderickson** [hmslincs/hmslincs#397]
see: 

http://lincs.hms.harvard.edu/db/sm/10029-101-001/

- importer converts "001" to int when performing batch lookup
- views.py should convert to int here https://github.com/hmslincs/hmslincs/blob/master/django/db/views.py#L597

**Comment by jmuhlich** [comment]
Ideally the importer should perform the same conversion on the stored data that it does for the verification lookup. Or raise an error so the curator can fix it. The view code shouldn't be dealing with this sort of thing.

**Comment by jmuhlich** [comment]
Solved temporarily via mod_rewrite:

`RewriteRule ^(db/sm/[0-9]+-[0-9]+-)00([0-9])/$ $1$2 [PT]`

Obviously this will need a proper fix in the long run.

**Comment by seanderickson** [comment]
Note: importer should store the converted batch_id here: https://github.com/hmslincs/hmslincs/blob/master/src/import_dataset2.py#L627 (and similar occurrences).
