### ISSUE TITLE
OMERO.web full viewer issue

### ISSUE THREAD

**Issue by jaycopeland** [hmslincs/hmslincs#403]
@seanderickson In Jerry's dataset there are two OMERO thumbnail images per row. If you want to compare the two images from a particular row you would normally open them in separate popup windows. As written now, the current javascript opens the popups in the same window. I suggest that the two columns should open to separate popup windows. Thanks! Jay

**Comment by seanderickson** [comment]
I put a simple fix (adding the image id to the window "title") on http://dev.oshernatprod.hms.harvard.edu/db/datasets/20236/results

Let me know if that helps this issue.

(note that the title is updated by the omero response)

**Comment by jmuhlich** [comment]
That's the window *name* not its title (title is a property of the 
document, not the window, anyway). And if you want a new window every 
time you can just use "_blank" for the window name rather than trying to 
create a unique string.

**Comment by seanderickson** [comment]
even easier - thanks!
