### ISSUE TITLE
db: associate multiple target proteins with an antibody

### ISSUE THREAD

**Issue by seanderickson** [hmslincs/hmslincs#442]
- the AR_Target_Protein field can reference multiple proteins
- the input file should reference the proteins by pr_center_specific_id

@liz-williams 
@jmuhlich 
@dwrobel1

**Comment by seanderickson** [comment]
@liz-williams 
There are two displayed fields for the target protein; now that the target protein will have multiple values, shall we:

1. Display as two ordered lists, as in: 
Nominal Protein Target(s): H31-phosphorylated, H32-non-phosphorylated
Nominal Protein Target HMS LINCS ID(s):	201294, 201295

2. Collapse the two fields into one combined field, as in:
Nominal Protein Target(s): H31-phosphorylated (HMSL201294), H32-non-phosphorylated (HMSL201295)

3. Show the Nominal Protein targets as a sub-table

Nominal Protein Targets: sub-table as:
![nominal_protein_targets](https://cloud.githubusercontent.com/assets/1074001/17937812/6ccde376-69f1-11e6-9eb6-d4232c017445.png)

In each case, the each value in the list would link to the protein page.

**Comment by liz-williams** [comment]
All of this will go away once PLN is implemented, so let's stick with the easiest solution in terms of DB implementation and DB data loading. Am I correct that that is option 1? If so, let's go with that with just one change: please make it a semicolon-separated list rather than a comma-separated one.

**Comment by seanderickson** [comment]
Options 1 and 2 are marginally simpler from a UI perspective, the db implementation would be the same in all cases.
I'll go with option 1, using semicolons.

**Comment by seanderickson** [comment]
Antibody and Protein search modifications:

Protein search: 
- return all proteins from the full text search fields, as usual
- return proteins having the same uniprot ID as those found by the full text search

Antibody Search:

- return antibodies referencing target proteins returned by the Protein Search
- return antibodies found from from the antibody full text search, as usual

@liz-williams @jmuhlich
